FROM ubuntu:20.04

RUN apt-get update -y
RUN apt-get install tesseract-ocr -y 
RUN apt-get install -y python3
RUN apt install -y python3-pip
RUN pip3 install pymongo[srv]
RUN pip3 install pika

WORKDIR /app

COPY . /app

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]
