FROM ubuntu:20.04
RUN apt-get update 
RUN apt-get install -y python3
RUN apt install -y python3-pip
RUN apt install -y curl
RUN pip3 install flask[async]
RUN pip3 install pymongo[srv]

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app

CMD [ "python3", "app.py"]

